export const  Add_TO_CART ="Add_TO_CART"
export const  Remove_TO_CART ="Remove_TO_CART"
export const  Empty_TO_CART ="Empty_TO_CART"
export const  PRODUCT_LIST ="PRODUCT_LIST"
export const  Set_PRODUCT_LIST ="Set_PRODUCT_LIST"
export const  Search_PRODUCT ="Search_PRODUCT"
